#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
TorchFX to NNTrainer Converter CLI.

Converts any HuggingFace CausalLM model to NNTrainer format by inspecting
the model's module hierarchy — no per-model converter files needed.

Usage:
    python convert.py --model Qwen/Qwen3-0.6B --output ./output/
    python convert.py --model google/gemma-3-1b --output ./output/

    # With custom runtime params:
    python convert.py --model Qwen/Qwen3-0.6B --output ./output/ \
        --init-seq-len 1024 --num-to-generate 512 --max-seq-len 2048

    # From local config file (config-only mode, no model download):
    python convert.py --model Qwen/Qwen3-0.6B --output ./output/ --config-only
"""

import argparse
import json
import os
import sys

from model_inspector import (
    inspect_model,
    generate_layers,
    generate_weight_order,
    generate_nntr_config,
    generate_weight_converter_script,
)


def convert_model(model, args, output_dir):
    """Convert any HuggingFace CausalLM model to NNTrainer format."""
    # Inspect model structure generically
    structure = inspect_model(model)

    # Override with CLI args
    if args.init_seq_len:
        structure.init_seq_len = args.init_seq_len
    if args.num_to_generate:
        structure.num_to_generate = args.num_to_generate
    if args.max_seq_len:
        structure.max_seq_len = args.max_seq_len
    if args.batch_size:
        structure.batch_size = args.batch_size
    if args.fc_dtype:
        structure.fc_layer_dtype = args.fc_dtype
    if args.embedding_dtype:
        structure.embedding_dtype = args.embedding_dtype

    model_name = args.model.split("/")[-1] if args.model else "model"
    safe_name = model_name.lower().replace("-", "_")

    # 1. Generate NNTrainer layers
    layers = generate_layers(structure)
    print(f"Generated {len(layers)} NNTrainer layers")

    # 2. Save layer definitions as JSON
    layers_json = [l.to_dict() for l in layers]
    layers_path = os.path.join(output_dir, "layers.json")
    with open(layers_path, "w") as f:
        json.dump(layers_json, f, indent=2)
    print(f"Saved layer definitions to {layers_path}")

    # 3. Generate and save nntr_config.json
    tokenizer_file = args.tokenizer_file or f"/path/to/{model_name}/tokenizer.json"
    sample_input = args.sample_input or ""
    nntr_config = generate_nntr_config(
        structure,
        model_file=f"nntr_{safe_name}_fp32.bin",
        tokenizer_file=tokenizer_file,
        sample_input=sample_input,
    )
    config_path = os.path.join(output_dir, "nntr_config.json")
    with open(config_path, "w") as f:
        json.dump(nntr_config, f, indent=4)
    print(f"Saved nntr_config.json to {config_path}")

    # 4. Generate weight conversion order
    weight_order = generate_weight_order(structure)
    weight_order_path = os.path.join(output_dir, "weight_order.json")
    with open(weight_order_path, "w") as f:
        json.dump(weight_order, f, indent=2)
    print(f"Saved weight order to {weight_order_path}")

    # 5. Generate weight converter script
    script = generate_weight_converter_script(structure, model_name)
    script_path = os.path.join(output_dir, "weight_converter.py")
    with open(script_path, "w") as f:
        f.write(script)
    os.chmod(script_path, 0o755)
    print(f"Saved weight converter to {script_path}")

    # 6. Generate C++ layer creation code
    cpp_lines = []
    cpp_lines.append("// Auto-generated by TorchFXConverter")
    cpp_lines.append(f"// Model: {model_name}")
    cpp_lines.append(f"// Layers: {len(layers)}")
    cpp_lines.append("")
    for layer in layers:
        cpp_lines.append(f"layers.push_back({layer.to_cpp_create_layer()});")
    cpp_path = os.path.join(output_dir, "create_layers.cpp")
    with open(cpp_path, "w") as f:
        f.write("\n".join(cpp_lines) + "\n")
    print(f"Saved C++ layer code to {cpp_path}")

    # Summary
    print(f"\n{'='*60}")
    print(f"Conversion complete for {model_name}")
    print(f"  Hidden size: {structure.hidden_size}")
    print(f"  Layers: {structure.num_layers}")
    print(f"  Attention heads: {structure.num_attention_heads} "
          f"(KV: {structure.num_key_value_heads})")
    print(f"  Head dim: {structure.head_dim}")
    print(f"  Intermediate size: {structure.intermediate_size}")
    print(f"  Vocab size: {structure.vocab_size}")
    print(f"  Tie embeddings: {structure.tie_word_embeddings}")
    if structure.layers:
        info = structure.layers[0]
        print(f"  Q/K norms: {info.has_qk_norm}")
        print(f"  Activation: {info.mlp_activation}")
        if info.has_post_attn_norm:
            print(f"  Post-attention norm: yes (Gemma3 style)")
    print(f"  NNTrainer layers: {len(layers)}")
    print(f"  Weight entries: {len(weight_order)}")
    print(f"\nOutput files in {output_dir}/:")
    print(f"  - nntr_config.json     (runtime config)")
    print(f"  - layers.json          (layer definitions)")
    print(f"  - weight_order.json    (weight mapping)")
    print(f"  - weight_converter.py  (HF -> NNTrainer weight converter)")
    print(f"  - create_layers.cpp    (C++ layer creation code)")
    print(f"{'='*60}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert HuggingFace CausalLM models to NNTrainer format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--model", type=str,
        help="HuggingFace model name or path (e.g., Qwen/Qwen3-0.6B)",
    )
    parser.add_argument(
        "--config", type=str,
        help="Path to local HuggingFace config.json (alternative to --model)",
    )
    parser.add_argument(
        "--output", type=str, required=True,
        help="Output directory for converted files",
    )
    parser.add_argument(
        "--config-only", action="store_true",
        help="Only generate config files without downloading the model",
    )

    # Runtime params
    parser.add_argument("--init-seq-len", type=int, default=1024)
    parser.add_argument("--num-to-generate", type=int, default=512)
    parser.add_argument("--max-seq-len", type=int, default=2048)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--fc-dtype", type=str, default="FP32")
    parser.add_argument("--embedding-dtype", type=str, default="FP32")
    parser.add_argument("--tokenizer-file", type=str, default=None)
    parser.add_argument("--sample-input", type=str, default="")

    args = parser.parse_args()

    if not args.model and not args.config:
        parser.error("Either --model or --config is required")

    # Create output directory
    os.makedirs(args.output, exist_ok=True)

    # Load model
    from transformers import AutoModelForCausalLM, AutoConfig

    if args.config:
        hf_config = AutoConfig.from_pretrained(args.config)
    else:
        hf_config = AutoConfig.from_pretrained(args.model, trust_remote_code=True)

    if args.config_only:
        # Config-only mode: create model from config without downloading weights
        model = AutoModelForCausalLM.from_config(hf_config, trust_remote_code=True)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            args.model or args.config,
            torch_dtype=torch.float32,
            trust_remote_code=True,
        )

    model.eval()

    model_type = getattr(hf_config, "model_type", "unknown")
    print(f"Loaded model: {args.model or args.config} (type: {model_type})")

    convert_model(model, args, args.output)


if __name__ == "__main__":
    import torch
    main()
