#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
TorchFX to NNTrainer Converter CLI.

Converts HuggingFace PyTorch models to NNTrainer format.

Usage:
    python convert.py --model Qwen/Qwen3-0.6B --output ./output/

    # With custom runtime params:
    python convert.py --model Qwen/Qwen3-0.6B --output ./output/ \
        --init-seq-len 1024 --num-to-generate 512 --max-seq-len 2048

    # Generate weight converter only (no model download needed):
    python convert.py --model Qwen/Qwen3-0.6B --output ./output/ --config-only

    # From local config file:
    python convert.py --config ./config.json --output ./output/
"""

import argparse
import json
import os
import sys

from qwen3_converter import (
    Qwen3Config,
    generate_qwen3_layers,
    generate_nntr_config,
    generate_weight_order,
    generate_weight_converter_script,
)


def detect_architecture(hf_config) -> str:
    """Detect the model architecture from HuggingFace config."""
    architectures = getattr(hf_config, "architectures", None) or []
    model_type = getattr(hf_config, "model_type", "") or ""

    if "Qwen3ForCausalLM" in architectures or model_type == "qwen3":
        return "qwen3"

    return "unknown"


def convert_qwen3(hf_config, args, output_dir):
    """Convert a Qwen3 model."""
    cfg = Qwen3Config.from_hf_config(hf_config)

    # Override with CLI args
    if args.init_seq_len:
        cfg.init_seq_len = args.init_seq_len
    if args.num_to_generate:
        cfg.num_to_generate = args.num_to_generate
    if args.max_seq_len:
        cfg.max_seq_len = args.max_seq_len
    if args.batch_size:
        cfg.batch_size = args.batch_size
    if args.fc_dtype:
        cfg.fc_layer_dtype = args.fc_dtype
    if args.embedding_dtype:
        cfg.embedding_dtype = args.embedding_dtype

    model_name = args.model.split("/")[-1] if args.model else "qwen3"
    safe_name = model_name.lower().replace("-", "_")

    # 1. Generate NNTrainer layers
    layers = generate_qwen3_layers(cfg)
    print(f"Generated {len(layers)} NNTrainer layers")

    # 2. Save layer definitions as JSON
    layers_json = [l.to_dict() for l in layers]
    layers_path = os.path.join(output_dir, "layers.json")
    with open(layers_path, "w") as f:
        json.dump(layers_json, f, indent=2)
    print(f"Saved layer definitions to {layers_path}")

    # 3. Generate and save nntr_config.json
    tokenizer_file = args.tokenizer_file or f"/path/to/{model_name}/tokenizer.json"
    sample_input = args.sample_input or ""
    nntr_config = generate_nntr_config(
        cfg,
        model_file=f"nntr_{safe_name}_fp32.bin",
        tokenizer_file=tokenizer_file,
        sample_input=sample_input,
    )
    config_path = os.path.join(output_dir, "nntr_config.json")
    with open(config_path, "w") as f:
        json.dump(nntr_config, f, indent=4)
    print(f"Saved nntr_config.json to {config_path}")

    # 4. Generate weight conversion order
    weight_order = generate_weight_order(cfg)
    weight_order_path = os.path.join(output_dir, "weight_order.json")
    with open(weight_order_path, "w") as f:
        json.dump(weight_order, f, indent=2)
    print(f"Saved weight order to {weight_order_path}")

    # 5. Generate weight converter script
    script = generate_weight_converter_script(cfg, model_name)
    script_path = os.path.join(output_dir, "weight_converter.py")
    with open(script_path, "w") as f:
        f.write(script)
    os.chmod(script_path, 0o755)
    print(f"Saved weight converter to {script_path}")

    # 6. Generate C++ layer creation code
    cpp_lines = []
    cpp_lines.append("// Auto-generated by TorchFXConverter")
    cpp_lines.append(f"// Model: {model_name}")
    cpp_lines.append(f"// Layers: {len(layers)}")
    cpp_lines.append("")
    for layer in layers:
        cpp_lines.append(f"layers.push_back({layer.to_cpp_create_layer()});")
    cpp_path = os.path.join(output_dir, "create_layers.cpp")
    with open(cpp_path, "w") as f:
        f.write("\n".join(cpp_lines) + "\n")
    print(f"Saved C++ layer code to {cpp_path}")

    # Summary
    print(f"\n{'='*60}")
    print(f"Conversion complete for {model_name}")
    print(f"  Architecture: Qwen3 CausalLM")
    print(f"  Hidden size: {cfg.hidden_size}")
    print(f"  Layers: {cfg.num_hidden_layers}")
    print(f"  Attention heads: {cfg.num_attention_heads} (KV: {cfg.num_key_value_heads})")
    print(f"  Head dim: {cfg.head_dim}")
    print(f"  Intermediate size: {cfg.intermediate_size}")
    print(f"  Vocab size: {cfg.vocab_size}")
    print(f"  Tie embeddings: {cfg.tie_word_embeddings}")
    print(f"  NNTrainer layers: {len(layers)}")
    print(f"  Weight entries: {len(weight_order)}")
    print(f"\nOutput files in {output_dir}/:")
    print(f"  - nntr_config.json     (runtime config)")
    print(f"  - layers.json          (layer definitions)")
    print(f"  - weight_order.json    (weight mapping)")
    print(f"  - weight_converter.py  (HF -> NNTrainer weight converter)")
    print(f"  - create_layers.cpp    (C++ layer creation code)")
    print(f"{'='*60}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert HuggingFace PyTorch models to NNTrainer format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--model", type=str,
        help="HuggingFace model name or path (e.g., Qwen/Qwen3-0.6B)",
    )
    parser.add_argument(
        "--config", type=str,
        help="Path to local HuggingFace config.json (alternative to --model)",
    )
    parser.add_argument(
        "--output", type=str, required=True,
        help="Output directory for converted files",
    )
    parser.add_argument(
        "--config-only", action="store_true",
        help="Only generate config files without downloading the model",
    )

    # Runtime params
    parser.add_argument("--init-seq-len", type=int, default=1024)
    parser.add_argument("--num-to-generate", type=int, default=512)
    parser.add_argument("--max-seq-len", type=int, default=2048)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--fc-dtype", type=str, default="FP32")
    parser.add_argument("--embedding-dtype", type=str, default="FP32")
    parser.add_argument("--tokenizer-file", type=str, default=None)
    parser.add_argument("--sample-input", type=str, default="")

    args = parser.parse_args()

    if not args.model and not args.config:
        parser.error("Either --model or --config is required")

    # Create output directory
    os.makedirs(args.output, exist_ok=True)

    # Load config
    if args.config:
        from transformers import AutoConfig
        hf_config = AutoConfig.from_pretrained(args.config)
    else:
        from transformers import AutoConfig
        hf_config = AutoConfig.from_pretrained(args.model, trust_remote_code=True)

    # Detect architecture
    arch = detect_architecture(hf_config)
    print(f"Detected architecture: {arch}")

    if arch == "qwen3":
        convert_qwen3(hf_config, args, args.output)
    else:
        print(f"Error: Unsupported architecture '{arch}'")
        print(f"  model_type: {getattr(hf_config, 'model_type', 'unknown')}")
        print(f"  architectures: {getattr(hf_config, 'architectures', [])}")
        print(f"\nCurrently supported: qwen3")
        sys.exit(1)


if __name__ == "__main__":
    main()
