"""
C++ code emitter for NNTrainer TorchFX converter.

Generates C++ source files that construct NNTrainer models using the
createLayer() / addLayer() API pattern, matching the style used in
Applications/CausalLM/causal_lm.cpp.

Phase 4.1 of the TorchFX converter pipeline (DESIGN.md).
"""

from pattern_detector import ModelStructure, TransformerBlockPattern
from nntrainer_layers import NNTrainerLayerDef


# =============================================================================
# C++ Code Templates
# =============================================================================

_HEADER_TEMPLATE = """\
// Auto-generated by TorchFX-to-NNTrainer converter
// Model: {model_type} ({arch_type})
// Source: HuggingFace {model_type}

#include <layer.h>
#include <model.h>

using LayerHandle = std::shared_ptr<ml::train::Layer>;
using ModelHandle = std::unique_ptr<ml::train::Model>;
using ml::train::createLayer;

"""

_CONSTANTS_TEMPLATE = """\
// Model constants
static constexpr unsigned int NUM_VOCAB = {vocab_size};
static constexpr int DIM = {hidden_size};
static constexpr int NUM_LAYERS = {num_layers};
static constexpr int NUM_HEADS = {num_heads};
static constexpr int NUM_KV_HEADS = {num_kv_heads};
static constexpr int HEAD_DIM = {head_dim};
static constexpr int INTERMEDIATE_SIZE = {intermediate_size};
static constexpr float NORM_EPS = {norm_eps}f;
{extra_constants}
"""


def _q(s):
    """Quote a string as a C++ string literal."""
    return f'"{s}"'


def _cpp_layer(layer_type, props):
    """Generate a createLayer() call as a list of C++ lines.

    Each prop is a raw C++ expression string.
    """
    lines = []
    lines.append('  layers.push_back(createLayer("' + layer_type + '", {')
    for i, p in enumerate(props):
        comma = "," if i < len(props) - 1 else ""
        lines.append("    " + p + comma)
    lines.append("  }));")
    return lines


# =============================================================================
# C++ Emitter
# =============================================================================

class CppEmitter:
    """Generates C++ model construction code from converter output."""

    def __init__(self, layers, structure):
        self.layers = layers
        self.structure = structure
        self._by_name = {l.name: l for l in layers}

    def emit(self):
        """Generate complete C++ source code."""
        parts = []
        parts.append(self._emit_header())
        parts.append(self._emit_constants())
        parts.append(self._emit_helpers())
        parts.append(self._emit_construct_model())
        return "\n".join(parts)

    def _emit_header(self):
        s = self.structure
        return _HEADER_TEMPLATE.format(
            model_type=s.model_type or "unknown",
            arch_type=s.arch_type or "unknown",
        )

    def _emit_constants(self):
        s = self.structure
        extra = []
        if s.rope_theta:
            extra.append(
                "static constexpr unsigned int ROPE_THETA = "
                + str(int(s.rope_theta)) + ";")
        if s.tie_word_embeddings:
            extra.append(
                "static constexpr bool TIE_WORD_EMBEDDINGS = true;")

        return _CONSTANTS_TEMPLATE.format(
            vocab_size=s.vocab_size,
            hidden_size=s.hidden_size,
            num_layers=s.num_layers,
            num_heads=s.num_heads,
            num_kv_heads=s.num_kv_heads,
            head_dim=s.head_dim,
            intermediate_size=s.intermediate_size,
            norm_eps=s.norm_eps or 1e-6,
            extra_constants="\n".join(extra),
        )

    def _emit_helpers(self):
        """Emit createAttention(), createMlp(), createTransformerBlock()."""
        parts = []
        if not self.structure.blocks:
            return ""

        b0 = self.structure.blocks[0]
        if b0.attention:
            parts.append(self._emit_attention_helper(b0))
        if b0.ffn:
            parts.append(self._emit_ffn_helper(b0))
        parts.append(self._emit_block_helper(b0))
        return "\n".join(parts)

    # =========================================================================
    # Attention Helper
    # =========================================================================

    def _emit_attention_helper(self, block):
        attn = block.attention
        has_qk_norm = attn.has_qk_norm
        has_rope = attn.has_rope
        L = []  # lines

        L.append("std::vector<LayerHandle> createAttention(")
        L.append("  const int layer_id, std::string input_name) {")
        L.append("")
        L.append("  std::vector<LayerHandle> layers;")
        L.append('  auto prefix = "layer" + std::to_string(layer_id);')
        L.append("")

        # Q projection
        L.append("  // Q projection")
        L.extend(_cpp_layer("fully_connected", [
            '"name=" + prefix + "_wq"',
            '"unit=" + std::to_string(HEAD_DIM * NUM_HEADS)',
            '"disable_bias=true"',
            '"input_layers=" + input_name',
        ]))

        # K projection
        L.append("")
        L.append("  // K projection")
        L.extend(_cpp_layer("fully_connected", [
            '"name=" + prefix + "_wk"',
            '"unit=" + std::to_string(HEAD_DIM * NUM_KV_HEADS)',
            '"disable_bias=true"',
            '"input_layers=" + input_name',
        ]))

        # V projection
        L.append("")
        L.append("  // V projection")
        L.extend(_cpp_layer("fully_connected", [
            '"name=" + prefix + "_wv"',
            '"unit=" + std::to_string(HEAD_DIM * NUM_KV_HEADS)',
            '"disable_bias=true"',
            '"input_layers=" + input_name',
        ]))

        # Q/K norms (Qwen3-style)
        if has_qk_norm:
            L.append("")
            L.append("  // Q norm (reshaped RMS norm)")
            L.extend(_cpp_layer("reshaped_rms_norm", [
                '"name=" + prefix + "_q_norm"',
                '"input_layers=" + prefix + "_wq"',
                '"packed=false"',
                '"epsilon=" + std::to_string(NORM_EPS)',
                '"feature_size=" + std::to_string(HEAD_DIM)',
            ]))

            L.append("")
            L.append("  // K norm (reshaped RMS norm)")
            L.extend(_cpp_layer("reshaped_rms_norm", [
                '"name=" + prefix + "_k_norm"',
                '"input_layers=" + prefix + "_wk"',
                '"packed=false"',
                '"epsilon=" + std::to_string(NORM_EPS)',
                '"feature_size=" + std::to_string(HEAD_DIM)',
            ]))

        # MHA core
        L.append("")
        L.append("  // Multi-head attention core")

        q_in = 'prefix + "_q_norm"' if has_qk_norm else 'prefix + "_wq"'
        k_in = 'prefix + "_k_norm"' if has_qk_norm else 'prefix + "_wk"'

        mha_props = [
            '"name=" + prefix + "_attention"',
            '"num_heads=" + std::to_string(NUM_HEADS)',
            '"num_heads_kv=" + std::to_string(NUM_KV_HEADS)',
        ]
        if has_rope:
            mha_props.append('"rope_theta=" + std::to_string(ROPE_THETA)')
        mha_props.append(
            '"input_layers=" + ' + q_in + ' + "," + '
            + k_in + ' + "," + prefix + "_wv"')
        L.extend(_cpp_layer("mha_core", mha_props))

        # O projection
        L.append("")
        L.append("  // Output projection")
        L.extend(_cpp_layer("fully_connected", [
            '"name=" + prefix + "_attention_out"',
            '"unit=" + std::to_string(DIM)',
            '"disable_bias=true"',
            '"input_layers=" + prefix + "_attention"',
        ]))

        L.append("")
        L.append("  return layers;")
        L.append("}")
        L.append("")
        return "\n".join(L)

    # =========================================================================
    # FFN Helper
    # =========================================================================

    def _emit_ffn_helper(self, block):
        ffn = block.ffn
        L = []

        L.append("std::vector<LayerHandle> createMlp(")
        L.append("  const int layer_id, std::string input_name) {")
        L.append("")
        L.append("  std::vector<LayerHandle> layers;")
        L.append('  auto prefix = "layer" + std::to_string(layer_id);')
        L.append("")

        if ffn.ffn_type == "swiglu":
            L.append("  // Up projection")
            L.extend(_cpp_layer("fully_connected", [
                '"name=" + prefix + "_ffn_up"',
                '"unit=" + std::to_string(INTERMEDIATE_SIZE)',
                '"disable_bias=true"',
                '"input_layers=" + input_name',
            ]))

            L.append("")
            L.append("  // Gate projection")
            L.extend(_cpp_layer("fully_connected", [
                '"name=" + prefix + "_ffn_gate"',
                '"unit=" + std::to_string(INTERMEDIATE_SIZE)',
                '"disable_bias=true"',
                '"input_layers=" + input_name',
            ]))

            L.append("")
            L.append("  // SwiGLU activation")
            L.extend(_cpp_layer("swiglu", [
                '"name=" + prefix + "_ffn_swiglu"',
                '"input_layers=" + prefix + "_ffn_up," + prefix + "_ffn_gate"',
            ]))

            L.append("")
            L.append("  // Down projection")
            L.extend(_cpp_layer("fully_connected", [
                '"name=" + prefix + "_ffn_down"',
                '"unit=" + std::to_string(DIM)',
                '"disable_bias=true"',
                '"input_layers=" + prefix + "_ffn_swiglu"',
            ]))
        else:
            act = "gelu" if ffn.ffn_type == "gelu_ffn" else "relu"
            L.append("  // FC1 (intermediate)")
            L.extend(_cpp_layer("fully_connected", [
                '"name=" + prefix + "_ffn_fc1"',
                '"unit=" + std::to_string(INTERMEDIATE_SIZE)',
                '"input_layers=" + input_name',
            ]))

            L.append("")
            L.append("  // Activation (" + act + ")")
            L.extend(_cpp_layer("activation", [
                '"name=" + prefix + "_ffn_act"',
                '"activation=' + act + '"',
                '"input_layers=" + prefix + "_ffn_fc1"',
            ]))

            L.append("")
            L.append("  // FC2 (output)")
            L.extend(_cpp_layer("fully_connected", [
                '"name=" + prefix + "_ffn_down"',
                '"unit=" + std::to_string(DIM)',
                '"input_layers=" + prefix + "_ffn_act"',
            ]))

        L.append("")
        L.append("  return layers;")
        L.append("}")
        L.append("")
        return "\n".join(L)

    # =========================================================================
    # Block Helper
    # =========================================================================

    def _emit_block_helper(self, block):
        s = self.structure
        norm_type = "rms_norm" if s.model_type not in (
            "bert", "roberta", "distilbert") else "layer_normalization"
        L = []

        L.append("std::vector<LayerHandle> createTransformerBlock(")
        L.append("  const int layer_id, std::string input_name) {")
        L.append("")
        L.append("  std::vector<LayerHandle> layers;")
        L.append('  auto prefix = "layer" + std::to_string(layer_id);')
        L.append("")

        # Pre-attention norm
        if block.pre_attn_norm:
            L.append("  // Pre-attention normalization")
            norm_props = [
                '"name=" + prefix + "_attention_norm"',
                '"input_layers=" + input_name',
                '"epsilon=" + std::to_string(NORM_EPS)',
            ]
            if norm_type == "rms_norm":
                norm_props.append('"packed=false"')
            L.extend(_cpp_layer(norm_type, norm_props))
            L.append("")

        # Attention
        if block.attention:
            attn_in = ('prefix + "_attention_norm"' if block.pre_attn_norm
                       else "input_name")
            L.append("  // Attention sub-layers")
            L.append("  auto att = createAttention(layer_id, "
                      + attn_in + ");")
            L.append("  layers.insert(layers.end(), att.begin(), att.end());")
            L.append("")

        # Attention residual
        if block.attn_residual:
            L.append("  // Attention residual connection")
            L.extend(_cpp_layer("addition", [
                '"name=" + prefix + "_attn_add"',
                '"input_layers=" + input_name + "," + '
                'prefix + "_attention_out"',
            ]))
            L.append("")

        # Pre-FFN norm
        if block.pre_ffn_norm:
            ffn_norm_in = ('prefix + "_attn_add"' if block.attn_residual
                           else 'prefix + "_attention_out"')
            L.append("  // Pre-FFN normalization")
            norm_props = [
                '"name=" + prefix + "_ffn_norm"',
                '"input_layers=" + ' + ffn_norm_in,
                '"epsilon=" + std::to_string(NORM_EPS)',
            ]
            if norm_type == "rms_norm":
                norm_props.append('"packed=false"')
            L.extend(_cpp_layer(norm_type, norm_props))
            L.append("")

        # FFN
        if block.ffn:
            ffn_in = ('prefix + "_ffn_norm"' if block.pre_ffn_norm
                      else 'prefix + "_attn_add"')
            L.append("  // FFN sub-layers")
            L.append("  auto ffn = createMlp(layer_id, " + ffn_in + ");")
            L.append("  layers.insert(layers.end(), ffn.begin(), ffn.end());")
            L.append("")

        # FFN residual
        if block.ffn_residual:
            res_in = ('prefix + "_attn_add"' if block.attn_residual
                      else "input_name")
            L.append("  // FFN residual connection")
            L.extend(_cpp_layer("addition", [
                '"name=" + prefix + "_block_output"',
                '"input_layers=" + ' + res_in + ' + "," + '
                'prefix + "_ffn_down"',
            ]))
            L.append("")

        L.append("  return layers;")
        L.append("}")
        L.append("")
        return "\n".join(L)

    # =========================================================================
    # constructModel()
    # =========================================================================

    def _emit_construct_model(self):
        s = self.structure
        L = []

        L.append("void constructModel(ModelHandle &model) {")
        L.append("")
        L.append("  std::vector<LayerHandle> layers;")
        L.append("")
        L.append("  // Create model")
        L.append("  model = ml::train::createModel("
                 "ml::train::ModelType::NEURAL_NET);")
        L.append("")

        # Input layer
        L.append("  // Input layer")
        L.extend(_cpp_layer("input", [
            '"name=input0"',
            '"input_shape=1:1:" + std::to_string(INIT_SEQ_LEN)',
        ]))
        L.append("")

        # Embedding
        if s.embedding:
            emb_type = ("tie_word_embeddings" if s.tie_word_embeddings
                        else "embedding_layer")
            L.append("  // Embedding layer")
            L.extend(_cpp_layer(emb_type, [
                '"name=embedding0"',
                '"in_dim=" + std::to_string(NUM_VOCAB)',
                '"out_dim=" + std::to_string(DIM)',
            ]))
            L.append("")

        # Transformer blocks loop
        L.append("  // Transformer blocks")
        L.append("  for (int i = 0; i < NUM_LAYERS; ++i) {")
        first_in = '"embedding0"' if s.embedding else '"input0"'
        L.append("    std::string input_name = (i == 0) ? " + first_in)
        L.append('      : "layer" + std::to_string(i - 1) + "_block_output";')
        L.append("    auto block = createTransformerBlock(i, input_name);")
        L.append("    layers.insert(layers.end(), block.begin(), "
                 "block.end());")
        L.append("  }")
        L.append("")

        # Final norm
        if s.final_norm:
            norm_type = ("rms_norm" if s.model_type not in ("bert", "roberta")
                         else "layer_normalization")
            L.append("  // Final normalization")
            norm_props = [
                '"name=output_norm"',
                '"input_layers=" + std::string("layer") + '
                'std::to_string(NUM_LAYERS - 1) + "_block_output"',
                '"epsilon=" + std::to_string(NORM_EPS)',
            ]
            if norm_type == "rms_norm":
                norm_props.append('"packed=false"')
            L.extend(_cpp_layer(norm_type, norm_props))
            L.append("")

        # LM head
        if s.lm_head:
            lm_type = ("tie_word_embeddings" if s.tie_word_embeddings
                       else "fully_connected")
            L.append("  // LM head")
            lm_props = [
                '"name=lm_head"',
                '"unit=" + std::to_string(NUM_VOCAB)',
                '"disable_bias=true"',
                '"input_layers=output_norm"',
            ]
            if s.tie_word_embeddings:
                lm_props.append('"shared_from=embedding0"')
            L.extend(_cpp_layer(lm_type, lm_props))
            L.append("")

        # Add all layers
        L.append("  // Add layers to model")
        L.append("  for (auto &layer : layers) {")
        L.append("    model->addLayer(layer);")
        L.append("  }")
        L.append("}")
        L.append("")
        return "\n".join(L)


# =============================================================================
# Convenience function
# =============================================================================

def emit_cpp(layers, structure):
    """Generate C++ model construction code.

    Args:
        layers: List of NNTrainerLayerDef from converter pipeline.
        structure: ModelStructure from pattern detection.

    Returns:
        str: Complete C++ source file content.
    """
    emitter = CppEmitter(layers, structure)
    return emitter.emit()
