// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Jijoong Moon
 *
 * @file   unittest_qnn_graph.cpp
 * @date   03 July 2026
 * @brief  Device-side (arm64) integration test: our QNNGraph layer loads an
 *         offline QNN HTP context binary and executes it on the Hexagon DSP
 *         through the nntrainer model API (engine=npu), then checks the output.
 *
 * This is the model-API path (Mode-1 whole-graph offload): a 1-layer model with
 * the `qnn_graph` layer whose FilePath points at the pre-generated .bin. The
 * model/graph infrastructure sets the RunLayerContext context-data (QNNBackendVar),
 * which QNNGraph::forwarding() consumes (getQNNVar) to run graphExecute on HTP.
 *
 * Fixtures (generated by the offline pipeline, see project_t13_t14_npu_mode1):
 *   conv_relu_htp_v81.bin  — InceptionV3 Conv2d_1a_3x3+Relu, HTP dsp_arch v81
 *   input_0.raw            — uint8 [1,299,299,3] (299*299*3 = 268203 bytes)
 *   golden_output.raw      — uint8 [1,149,149,32] (149*149*32 = 710432 bytes)
 * QNN graph name = "convReluModel" (the qnn_graph LAYER NAME must match it, so
 * QNNGraph::forwarding()'s graphRetrieve(bin, context.getName()) resolves).
 * Quant: input_0  scale=0.0078119998797774315 offset=-128
 *        output   scale=0.05470849946141243   offset=0
 *
 * Usage (on device):
 *   ./unittest_qnn_graph <dir-with-fixtures>
 * with LD_LIBRARY_PATH=<runtime dir> and
 *      ADSP_LIBRARY_PATH="<dir>;/vendor/lib/rfsa/adsp;/vendor/dsp/cdsp"
 * and the aarch64-android QNN runtime + the unsigned hexagon-v81 skel present.
 *
 * @note  NOT yet run/verified on device — first-ever qnn_graph model wiring.
 *        Points likely to need on-device iteration are marked TODO(verify).
 */

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

#include <layer.h>
#include <model.h>
#include <tensor_api.h>

using ml::train::createLayer;
using ml::train::createModel;
using ml::train::LayerHandle;

namespace {

constexpr unsigned int IN_ELEMS = 1u * 299u * 299u * 3u;   // 268203
constexpr unsigned int OUT_ELEMS = 1u * 149u * 149u * 32u; // 710432

/** Input tensor quant encoding (from the .bin metadata). */
constexpr float IN_SCALE = 0.0078119998797774315f;
constexpr int IN_OFFSET = -128;
/** Output tensor quant encoding. */
constexpr float OUT_SCALE = 0.05470849946141243f;
constexpr int OUT_OFFSET = 0;

/** The QNN graph name inside the .bin — also the qnn_graph layer name. */
const std::string GRAPH_NAME = "convrelumodel";
/** QNN tensor names (from metadata) — used for the per-tensor quant props. */
const std::string IN_TENSOR_NAME = "input_0";
const std::string OUT_TENSOR_NAME =
  "InceptionV3_InceptionV3_Conv2d_1a_3x3_Relu_0";

std::vector<uint8_t> readRaw(const std::string &path) {
  std::ifstream f(path, std::ios::binary);
  if (!f)
    return {};
  return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),
                              std::istreambuf_iterator<char>());
}

} // namespace

int main(int argc, char **argv) {
  setvbuf(stdout, nullptr, _IONBF, 0); // unbuffered: keep progress on abort
  setvbuf(stderr, nullptr, _IONBF, 0);
  const std::string dir = (argc > 1) ? argv[1] : ".";
  const std::string bin_path = dir + "/conv_relu_htp_v81.bin";
  const std::string in_path = dir + "/input_0.raw";
  const std::string golden_path = dir + "/golden_output.raw";

  // ---- load fixtures --------------------------------------------------------
  std::vector<uint8_t> in_u8 = readRaw(in_path);
  std::vector<uint8_t> golden_u8 = readRaw(golden_path);
  if (in_u8.size() != IN_ELEMS) {
    std::fprintf(stderr, "[FAIL] input_0.raw size %zu != %u\n", in_u8.size(),
                 IN_ELEMS);
    return 1;
  }

  // QNNGraph takes FLOAT activations and (re)quantizes with the input quant
  // encoding. Dequantize the uint8 fixture so re-quantization reproduces the
  // exact bytes qnn-net-run consumed: float = (u8 - offset) * scale.
  std::vector<float> in_f(IN_ELEMS);
  for (unsigned int i = 0; i < IN_ELEMS; ++i)
    in_f[i] = (static_cast<int>(in_u8[i]) - IN_OFFSET) * IN_SCALE;

  // ---- build the model: input -> qnn_graph ---------------------------------
  auto model = createModel(ml::train::ModelType::NEURAL_NET, {"batch_size=1"});

  // createLayer returns unique_ptr<Layer>; ml::train::LayerHandle is the new-API
  // wrapper (implicit from unique_ptr, and implicitly convertible back to the
  // shared_ptr<Layer> that Model::addLayer takes).
  // Experiment: no separate cpu "input" layer — make qnn_graph the sole/first
  // layer so its input tensor is planned under the npu context (QNNRpcManager
  // rpcmem allocator), avoiding the cpu->npu boundary where rpcmem_to_fd fails.
  const bool USE_INPUT_LAYER =
    std::getenv("QNN_TEST_INPUT_LAYER") != nullptr;
  LayerHandle input;
  if (USE_INPUT_LAYER)
    input = createLayer("input", {"name=in", "input_shape=299:299:3"});

  // qnn_graph: LAYER NAME == QNN graph name; dim/data_type/tensor_type are
  // parallel vectors over [input, output]. The per-tensor QUANT PARAMS are NOT
  // passed here: they (and the tensor names/dims/dtypes) are embedded in the
  // serialized .bin and read at load via systemContextGetBinaryInfo, so
  // QNNGraph uses the .bin's encoding by default (input_quant_param /
  // output_quant_param remain an optional override). See the metadata dumped by
  // `qnn-context-binary-utility --json_file` (ctx_meta.json fixture).
  // TODO(verify): data_type enum spelling for uint8 QNN tensors, and whether
  // the IN_TENSOR entry is required or the input dim comes purely from the
  // graph connection. A follow-up can also derive dim/dtype from the .bin
  // (needs makeContext at finalize instead of lazily in forwarding).
  (void)IN_TENSOR_NAME;
  (void)OUT_TENSOR_NAME;
  LayerHandle qnn = createLayer(
    "qnn_graph",
    {
      "name=" + GRAPH_NAME,
      "engine=npu",
      "path=" + bin_path,
      "input_shape=299:299:3",
      "dim=1:299:299:3,1:149:149:32",
      "tensor_dtype=UINT8,UINT8",
      "tensor_type=IN_TENSOR,OUT_TENSOR",
    });

  try {
    if (USE_INPUT_LAYER)
      model->addLayer(input);
    model->addLayer(qnn);
    model->compile();
    model->initialize();
  } catch (const std::exception &e) {
    std::fprintf(stderr, "[FAIL] model build: %s\n", e.what());
    return 1;
  }

  // ---- inference ------------------------------------------------------------
  std::fprintf(stderr, "[dbg] model built; running inference on HTP...\n");
  std::vector<float *> inputs = {in_f.data()};
  std::vector<float *> out;
  try {
    out = model->inference(1, inputs);
    std::fprintf(stderr, "[dbg] inference returned (%zu outputs)\n", out.size());
  } catch (const std::exception &e) {
    std::fprintf(stderr, "[FAIL] inference (HTP execute): %s\n", e.what());
    return 1;
  }
  if (out.empty() || out[0] == nullptr) {
    std::fprintf(stderr, "[FAIL] inference returned no output\n");
    return 1;
  }

  // The QNN graph output tensor is native uint8 (OUT_ELEMS bytes); inference()
  // hands back its buffer typed as float* but it is really uint8 data. Read it
  // as bytes (reading it as float would overrun 4x).
  const uint8_t *o = reinterpret_cast<const uint8_t *>(out[0]);

  // ---- checks ---------------------------------------------------------------
  // (1) output is non-trivial (real HTP computation, not zeros).
  unsigned int nonzero = 0;
  for (unsigned int i = 0; i < OUT_ELEMS; ++i)
    if (o[i] != 0)
      ++nonzero;
  if (nonzero == 0) {
    std::fprintf(stderr, "[FAIL] output all-zero — graph did not compute\n");
    return 1;
  }
  std::printf("[ok] output non-zero: %u/%u\n", nonzero, OUT_ELEMS);

  // (2) golden compare. qnn-net-run matches its I/O dtype to the INPUT dtype:
  //     a FLOAT input (what this test feeds, and what QNNGraph quantizes) yields
  //     a dequantized FLOAT golden of OUT_ELEMS*4 bytes; a native uint8 input
  //     yields a uint8 golden of OUT_ELEMS bytes. Our output is native uint8, so
  //     DEQUANTIZE it (o*scale) to compare against the float golden.
  if (golden_u8.size() == OUT_ELEMS * sizeof(float)) {
    const float *g = reinterpret_cast<const float *>(golden_u8.data());
    double max_abs = 0.0, sum_abs = 0.0;
    for (unsigned int i = 0; i < OUT_ELEMS; ++i) {
      float deq = (static_cast<int>(o[i]) - OUT_OFFSET) * OUT_SCALE;
      double d = std::fabs(static_cast<double>(deq) - g[i]);
      max_abs = std::max(max_abs, d);
      sum_abs += d;
    }
    std::printf("[ok] vs float golden: mean_abs=%.6g max_abs=%.6g (1 step=%.6g)\n",
                sum_abs / OUT_ELEMS, max_abs, OUT_SCALE);
    if (max_abs > 1.5 * OUT_SCALE) { // within ~1 quant step everywhere
      std::fprintf(stderr, "[FAIL] output diverges from golden\n");
      return 1;
    }
  } else if (golden_u8.size() == OUT_ELEMS) {
    unsigned int exact = 0, off_by_1 = 0, worse = 0;
    for (unsigned int i = 0; i < OUT_ELEMS; ++i) {
      int d = std::abs(static_cast<int>(o[i]) - static_cast<int>(golden_u8[i]));
      (d == 0 ? exact : (d == 1 ? off_by_1 : worse))++;
    }
    std::printf("[ok] vs uint8 golden: exact=%u off1=%u worse=%u / %u\n", exact,
                off_by_1, worse, OUT_ELEMS);
    if (worse > OUT_ELEMS / 1000) {
      std::fprintf(stderr, "[FAIL] output diverges from golden\n");
      return 1;
    }
  } else {
    std::printf("[warn] golden size %zu unexpected — non-zero only\n",
                golden_u8.size());
  }

  std::printf("[PASS] QNNGraph loaded conv_relu_htp_v81.bin and executed on HTP\n");
  return 0;
}
