"""C++ code emitter package for NNTrainer TorchFX converter.

Generates class-based C++ header (.h) and source (.cpp) files that construct
NNTrainer models. The emitter is split into focused sub-modules:
  - helpers.py          : C++ code gen utilities and naming
  - header.py           : Header file generation
  - source_construct.py : constructModel() generation
  - source_block.py     : createTransformerBlock() generation
  - source_attention.py : createAttention() generation
  - source_ffn.py       : createMlp() generation
  - source_custom.py    : registerCustomLayers() generation
"""

import sys
import os

from emitter_base import BaseEmitter
from .helpers import (
    _q, _cpp_layer, _with_key,
    _class_name, _file_basename, _header_guard,
    _sanitize_model_name, get_output_filenames,
    get_file_base, get_norm_type,
)
from .header import emit_flat_header, emit_structured_header
from .source_construct import emit_flat_source, emit_construct_model
from .source_block import emit_block_method
from .source_attention import emit_attention_method
from .source_ffn import emit_ffn_method
from .source_custom import (
    collect_custom_layer_classes, emit_register_custom_layers,
    emit_custom_layer_includes, emit_initialize,
    CUSTOM_LAYER_CLASS,
)

# Re-export for backward compatibility
sys.modules.setdefault(
    "emitter_cpp.helpers",
    sys.modules[__name__ + ".helpers"]
)


class CppEmitter(BaseEmitter):
    """Generates class-based C++ header and source code from converter output.

    Orchestrates the sub-modules to produce the complete C++ output.
    """

    def __init__(self, layers, structure, model_name=None):
        super().__init__(layers, structure, model_name=model_name)

    def emit(self):
        """Generate combined C++ code (header + source)."""
        return self.emit_header() + "\n" + self.emit_source()

    # ----- Header -----

    def emit_header(self):
        """Generate C++ header file (.h) content."""
        if self._is_flat_model():
            return emit_flat_header(self.structure, self._model_name)
        return emit_structured_header(
            self.structure, self._blocks_info(), self._model_name)

    # ----- Source -----

    def emit_source(self):
        """Generate C++ source file (.cpp) content."""
        if self._is_flat_model():
            return emit_flat_source(
                self.layers, self.structure, self._model_name)
        return self._emit_structured_source()

    def _emit_structured_source(self):
        """Generate source for transformer models (block-based structure)."""
        s = self.structure
        cname = _class_name(s.model_type, s.arch_type)
        block_type = ("DecoderBlock" if s.arch_type == "decoder_only"
                      else "Block")
        header_file = get_file_base(s, self._model_name) + ".h"

        # Collect custom classes early (needed for includes)
        norm_type = get_norm_type(s.model_type)
        attn_block = self._get_attn_block()
        custom_classes = collect_custom_layer_classes(
            s, norm_type, attn_block)

        L = []
        L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
        L.append(f"// Model: {s.model_type} ({s.arch_type})")
        L.append(f"")
        L.append(f'#include "{header_file}"')
        L.append(f"#include <model.h>")
        L.append(f"#include <app_context.h>")
        L.append(f"#include <engine.h>")
        L.append(f"")
        includes = emit_custom_layer_includes(custom_classes)
        if includes:
            L.append(includes)
            L.append(f"")
        L.append(f"using ml::train::createLayer;")
        L.append(f"")

        # withKey helper templates
        L.append("template <typename T>")
        L.append('static std::string withKey(const std::string &key, T val) {')
        L.append('  return key + "=" + std::to_string(val);')
        L.append("}")
        L.append("")
        L.append("template <>")
        L.append('std::string withKey(const std::string &key, '
                 'std::string val) {')
        L.append('  return key + "=" + val;')
        L.append("}")
        L.append("")
        L.append("template <>")
        L.append('std::string withKey(const std::string &key, '
                 'const char *val) {')
        L.append('  return key + "=" + std::string(val);')
        L.append("}")
        L.append("")

        # Default constructor
        L.append(f"{cname}::{cname}() = default;")
        L.append("")

        # constructModel
        if s.arch_type == "encoder_decoder":
            bt = None
        else:
            bt = block_type
        blocks_info = {
            "op_type_list": [b.operator_type for b in s.blocks],
        }
        L.append(emit_construct_model(s, bt, self._is_hybrid_model(),
                                      blocks_info))

        # Block methods
        if s.arch_type == "encoder_decoder":
            self._emit_enc_dec_blocks(L, cname, s)
        elif s.blocks:
            self._emit_standard_blocks(L, cname, block_type, s)

        # registerCustomLayers (custom_classes already collected above)
        L.append(emit_register_custom_layers(cname, custom_classes))

        # initialize()
        L.append(emit_initialize(cname))

        return "\n".join(L)

    def _emit_enc_dec_blocks(self, L, cname, s):
        """Emit encoder/decoder block methods."""
        enc_blocks = s.encoder_blocks
        dec_blocks = s.decoder_blocks
        enc_b0 = enc_blocks[0] if enc_blocks else None
        dec_b0 = dec_blocks[0] if dec_blocks else None

        if enc_b0:
            L.append(emit_block_method(
                cname, "EncoderBlock", enc_b0, s, is_encoder=True))
        if dec_b0:
            L.append(emit_block_method(
                cname, "DecoderBlock", dec_b0, s, is_encoder=False))

        representative = enc_b0 or dec_b0
        if representative and representative.attention:
            L.append(emit_attention_method(cname, representative))
        if representative and representative.ffn:
            L.append(emit_ffn_method(cname, representative))

    def _emit_standard_blocks(self, L, cname, block_type, s):
        """Emit standard block methods."""
        op_types = self._get_operator_types()
        for op_type in op_types:
            rep_block = self._get_block_by_operator(op_type)
            L.append(emit_block_method(cname, block_type, rep_block, s))

        attn_block = self._get_attn_block()
        if attn_block:
            L.append(emit_attention_method(cname, attn_block))

        representative = next((b for b in s.blocks if b.ffn), None)
        if representative:
            L.append(emit_ffn_method(cname, representative))

    # ----- Internal helpers -----

    def _is_flat_model(self):
        return not self.structure.blocks

    def _get_operator_types(self):
        types = set()
        for b in self.structure.blocks:
            types.add(b.operator_type)
        return sorted(types)

    def _is_hybrid_model(self):
        return len(self._get_operator_types()) > 1

    def _get_attn_block(self):
        for b in self.structure.blocks:
            if b.attention is not None:
                return b
        return None

    def _get_block_by_operator(self, operator_type):
        for b in self.structure.blocks:
            if b.operator_type == operator_type:
                return b
        return None

    def _blocks_info(self):
        """Build blocks_info dict for header generation."""
        return {
            "attn_block": self._get_attn_block(),
            "is_hybrid": self._is_hybrid_model(),
            "op_types": self._get_operator_types(),
        }

    # Backward compatibility attributes
    _CUSTOM_LAYER_CLASS = CUSTOM_LAYER_CLASS

    def _get_norm_type(self):
        return get_norm_type(self.structure.model_type)

    def _file_base(self):
        return get_file_base(self.structure, self._model_name)

    def _collect_custom_layer_classes(self):
        norm_type = get_norm_type(self.structure.model_type)
        attn_block = self._get_attn_block()
        return collect_custom_layer_classes(
            self.structure, norm_type, attn_block)


# =============================================================================
# Convenience functions (backward compatible)
# =============================================================================

def emit_cpp(layers, structure, model_name=None):
    """Generate combined C++ code (header + source)."""
    return CppEmitter(layers, structure, model_name=model_name).emit()


def emit_cpp_header(layers, structure, model_name=None):
    """Generate C++ header file (.h) content."""
    return CppEmitter(layers, structure, model_name=model_name).emit_header()


def emit_cpp_source(layers, structure, model_name=None):
    """Generate C++ source file (.cpp) content."""
    return CppEmitter(layers, structure, model_name=model_name).emit_source()
