"""C++ header file (.h) generation for NNTrainer models."""

from .helpers import _class_name, get_file_base


def emit_flat_header(structure, model_name=None):
    """Generate header for non-transformer models (flat layer list)."""
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    base = get_file_base(s, model_name)
    guard = f"__{base.upper()}_H__"

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type}")
    L.append(f"")
    L.append(f"#ifndef {guard}")
    L.append(f"#define {guard}")
    L.append(f"")
    L.append(f"#include <layer.h>")
    L.append(f"#include <model.h>")
    L.append(f"")
    L.append(f"using LayerHandle = std::shared_ptr<ml::train::Layer>;")
    L.append(f"using ModelHandle = std::unique_ptr<ml::train::Model>;")
    L.append(f"")
    L.append(f"/**")
    L.append(f" * @brief {cname} Class")
    L.append(f" * @note Auto-generated from {s.model_type} model")
    L.append(f" */")
    L.append(f"class {cname} {{")
    L.append(f"")
    L.append(f"public:")
    L.append(f"  {cname}();")
    L.append(f"  virtual ~{cname}() = default;")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Construct the model graph")
    L.append(f"   */")
    L.append(f"  virtual void constructModel();")
    L.append(f"")
    L.append(f"protected:")
    L.append(f"  ModelHandle model;")
    L.append(f"}};")
    L.append(f"")
    L.append(f"#endif // {guard}")
    L.append(f"")
    return "\n".join(L)


def emit_structured_header(structure, blocks_info, model_name=None):
    """Generate header for transformer models (block-based structure).

    Args:
        structure: ModelStructure
        blocks_info: dict with keys:
            - attn_block: first block with attention (or None)
            - is_hybrid: bool
            - op_types: sorted list of unique operator types
        model_name: optional model name override
    """
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    base = get_file_base(s, model_name)
    guard = f"__{base.upper()}_H__"

    attn_block = blocks_info["attn_block"]
    is_hybrid = blocks_info["is_hybrid"]
    op_types = blocks_info["op_types"]

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type} ({s.arch_type})")
    L.append(f"")
    L.append(f"#ifndef {guard}")
    L.append(f"#define {guard}")
    L.append(f"")
    L.append(f"#include <layer.h>")
    L.append(f"#include <model.h>")
    L.append(f"")

    has_qk_norm = attn_block and attn_block.attention.has_qk_norm
    if has_qk_norm:
        L.append(f"#include <reshaped_rms_norm.h>")
        L.append(f"")

    L.append(f"using LayerHandle = std::shared_ptr<ml::train::Layer>;")
    L.append(f"using ModelHandle = std::unique_ptr<ml::train::Model>;")
    L.append(f"")

    L.append(f"/**")
    L.append(f" * @brief {cname} Class")
    L.append(f" * @note Auto-generated from HuggingFace {s.model_type} model")
    L.append(f" */")
    L.append(f"class {cname} {{")
    L.append(f"")
    L.append(f"public:")
    L.append(f"  {cname}();")
    L.append(f"  virtual ~{cname}() = default;")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Construct the model graph")
    L.append(f"   */")
    L.append(f"  virtual void constructModel();")
    L.append(f"")
    L.append(f"protected:")

    # Block creation methods
    if s.arch_type == "encoder_decoder":
        _emit_enc_dec_block_decls(L)
    else:
        block_type = ("DecoderBlock" if s.arch_type == "decoder_only"
                      else "Block")
        for op_type in op_types:
            op_label = op_type.capitalize() if op_type != "attention" \
                else "Transformer"
            L.append(f"  /**")
            L.append(f"   * @brief Create a {op_label} {block_type}")
            L.append(f"   */")
            L.append(f"  virtual std::vector<LayerHandle>")
            method_name = (f"createTransformer{block_type}"
                           if op_type == "attention"
                           else f"create{op_label}{block_type}")
            L.append(f"  {method_name}("
                     f"const int layer_id, std::string input_name);")
            L.append(f"")

    # createAttention
    if attn_block:
        L.append(f"  /**")
        L.append(f"   * @brief Create Attention layers")
        L.append(f"   */")
        L.append(f"  virtual std::vector<LayerHandle>")
        L.append(f"  createAttention(const int layer_id, int seq_len, "
                 f"int n_heads, int head_dim,")
        L.append(f"                  std::string query_name, "
                 f"std::string key_name,")
        L.append(f"                  std::string value_name);")
        L.append(f"")

    # createMlp
    L.append(f"  /**")
    L.append(f"   * @brief Create Feed Forward layers")
    L.append(f"   */")
    L.append(f"  virtual std::vector<LayerHandle>")
    L.append(f"  createMlp(const int layer_id, int dim, int hidden_dim,")
    L.append(f"            std::string input_name);")
    L.append(f"")

    # registerCustomLayers
    L.append(f"  /**")
    L.append(f"   * @brief Register custom layers")
    L.append(f"   */")
    L.append(f"  virtual void registerCustomLayers();")
    L.append(f"")

    # Member variables
    _emit_member_variables(L, s, attn_block)

    L.append(f"}};")
    L.append(f"")
    L.append(f"#endif // {guard}")
    L.append(f"")
    return "\n".join(L)


def _emit_enc_dec_block_decls(L):
    """Emit encoder/decoder block method declarations."""
    L.append(f"  /**")
    L.append(f"   * @brief Create a Transformer Encoder Block")
    L.append(f"   */")
    L.append(f"  virtual std::vector<LayerHandle>")
    L.append(f"  createEncoderBlock("
             f"const int layer_id, std::string input_name);")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Create a Transformer Decoder Block")
    L.append(f"   */")
    L.append(f"  virtual std::vector<LayerHandle>")
    L.append(f"  createDecoderBlock("
             f"const int layer_id, std::string input_name,")
    L.append(f"                     "
             f"std::string encoder_output);")
    L.append(f"")


def _emit_member_variables(L, s, attn_block):
    """Emit class member variable declarations."""
    L.append(f"  ModelHandle model;")
    L.append(f"")
    L.append(f"  // Model constants")
    L.append(f"  unsigned int NUM_VOCAB = {s.vocab_size};")
    L.append(f"  int DIM = {s.hidden_size};")
    if s.arch_type == "encoder_decoder":
        L.append(f"  int NUM_ENCODER_LAYERS = {s.num_encoder_layers};")
        L.append(f"  int NUM_DECODER_LAYERS = {s.num_decoder_layers};")
    L.append(f"  int NUM_LAYERS = {s.num_layers};")
    L.append(f"  int NUM_HEADS = {s.num_heads};")
    L.append(f"  int NUM_KV_HEADS = {s.num_kv_heads};")
    L.append(f"  int HEAD_DIM = {s.head_dim};")
    L.append(f"  int INTERMEDIATE_SIZE = {s.intermediate_size};")
    L.append(f"  float NORM_EPS = {s.norm_eps or 1e-6}f;")
    if s.rope_theta:
        L.append(f"  unsigned int ROPE_THETA = {int(s.rope_theta)};")
    L.append(f"  bool TIE_WORD_EMBEDDINGS = "
             f"{'true' if s.tie_word_embeddings else 'false'};")

    if s.num_kv_heads and s.num_heads:
        gqa = s.num_heads // s.num_kv_heads
        L.append(f"  int GQA_SIZE = {gqa};")

    if attn_block:
        L.append(f"  unsigned int SLIDING_WINDOW = UINT_MAX;")

    if s.conv_l_cache:
        L.append(f"  int CONV_KERNEL_SIZE = {s.conv_l_cache};")

    L.append(f"  unsigned int INIT_SEQ_LEN = 0;")
    L.append(f"  unsigned int NUM_TO_GENERATE = 0;")
    if attn_block and attn_block.attention.has_rope:
        L.append(f"  unsigned int MAX_POSITION_EMBEDDINGS = "
                 f"{s.max_position_embeddings or 2048};")
