"""C++ constructModel() method generation."""

from .helpers import _cpp_layer, _class_name, get_file_base, get_norm_type


def emit_flat_source(layers, structure, model_name=None):
    """Generate source for non-transformer models (flat layer list)."""
    from .source_custom import emit_register_custom_layers
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    header_file = get_file_base(s, model_name) + ".h"

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type}")
    L.append(f"")
    L.append(f'#include "{header_file}"')
    L.append(f"#include <model.h>")
    L.append(f"#include <app_context.h>")
    L.append(f"#include <engine.h>")
    L.append(f"")
    L.append(f"using ml::train::createLayer;")
    L.append(f"")

    # withKey helpers (needed for initialize)
    L.append("template <typename T>")
    L.append("__attribute__((unused))")
    L.append('static std::string withKey(const std::string &key, T val) {')
    L.append('  return key + "=" + std::to_string(val);')
    L.append("}")
    L.append("")
    L.append("__attribute__((unused))")
    L.append("static std::string withKey(const std::string &key, "
             "const char *val) {")
    L.append('  return key + "=" + std::string(val);')
    L.append("}")
    L.append("")

    # Default constructor
    L.append(f"{cname}::{cname}() = default;")
    L.append(f"")

    L.append(f"void {cname}::constructModel() {{")
    L.append(f"")
    L.append(f"  std::vector<std::shared_ptr<ml::train::Layer>> layers;")
    L.append(f"")
    L.append(f"  // Create model")
    L.append(f"  model = ml::train::createModel("
             f"ml::train::ModelType::NEURAL_NET);")
    L.append(f"")

    for layer in layers:
        L.append(f"  // {layer.layer_type}: {layer.name}")
        props = []
        for p in layer.to_properties_list():
            props.append(f'"{p}"')
        L.extend(_cpp_layer(layer.layer_type, props))
        L.append(f"")

    L.append(f"  // Add layers to model")
    L.append(f"  for (auto &layer : layers) {{")
    L.append(f"    model->addLayer(layer);")
    L.append(f"  }}")
    L.append(f"}}")
    L.append(f"")

    # registerCustomLayers (empty for flat models)
    L.append(emit_register_custom_layers(cname, []))

    # initialize (simplified for flat models - no INIT_SEQ_LEN)
    L.append(f"void {cname}::initialize() {{")
    L.append(f"  registerCustomLayers();")
    L.append(f"  constructModel();")
    L.append(f"")
    L.append(f"  model->setProperty({{")
    L.append(f'    withKey("batch_size", 1),')
    L.append(f'    withKey("epochs", "1"),')
    L.append(f'    withKey("model_tensor_type", "FP32-FP32")')
    L.append(f"  }});")
    L.append(f"")
    L.append(f"  if (model->compile(ml::train::ExecutionMode::INFERENCE)) {{")
    L.append(f'    throw std::invalid_argument("Model compilation failed.");')
    L.append(f"  }}")
    L.append(f"")
    L.append(f"  if (model->initialize(ml::train::ExecutionMode::INFERENCE)) {{")
    L.append(f'    throw std::invalid_argument("Model initialization failed.");')
    L.append(f"  }}")
    L.append(f"}}")
    L.append(f"")

    return "\n".join(L)


def emit_construct_model(structure, block_type, is_hybrid, blocks_info):
    """Generate constructModel() method body.

    Args:
        structure: ModelStructure
        block_type: "DecoderBlock", "Block", or None (encoder_decoder)
        is_hybrid: bool - whether model has multiple operator types
        blocks_info: dict with op_type_list, norm_type, etc.
    """
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    norm_type = get_norm_type(s.model_type)
    L = []

    L.append(f"void {cname}::constructModel() {{")
    L.append(f"")
    L.append(f"  std::vector<LayerHandle> layers;")
    L.append(f"")
    L.append(f"  // Create model")
    L.append(f"  model = ml::train::createModel("
             f"ml::train::ModelType::NEURAL_NET);")
    L.append(f"")

    # Input layer
    L.append(f"  // Input layer")
    L.extend(_cpp_layer("input", [
        'withKey("name", "input0")',
        'withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))',
    ]))
    L.append(f"")

    # Embedding
    if s.embedding:
        _emit_embedding(L, s)

    first_in = '"embedding0"' if s.embedding else '"input0"'

    if s.arch_type == "encoder_decoder":
        _emit_encoder_decoder_blocks(L, s, first_in, norm_type)
    elif is_hybrid:
        _emit_hybrid_blocks(L, s, first_in, block_type, blocks_info)
    else:
        _emit_standard_blocks(L, first_in, block_type)

    # Final norm (non-encoder-decoder)
    if s.arch_type != "encoder_decoder" and s.final_norm:
        _emit_final_norm(L, norm_type)

    # LM head
    if s.lm_head:
        _emit_lm_head(L, s)

    # Add all layers
    L.append(f"  // Add layers to model")
    L.append(f"  for (auto &layer : layers) {{")
    L.append(f"    model->addLayer(layer);")
    L.append(f"  }}")
    L.append(f"}}")
    L.append(f"")
    return "\n".join(L)


def _emit_embedding(L, s):
    """Emit embedding layer section."""
    L.append(f"  // Embedding layer")
    if s.tie_word_embeddings:
        L.append(f'  const std::string embedding_type = '
                 f'TIE_WORD_EMBEDDINGS ? '
                 f'"tie_word_embeddings" : "embedding_layer";')
    else:
        L.append(f'  const std::string embedding_type = '
                 f'"embedding_layer";')
    L.extend(_cpp_layer("\" + embedding_type + \"", [
        'withKey("name", "embedding0")',
        'withKey("in_dim", NUM_VOCAB)',
        'withKey("out_dim", DIM)',
    ]))
    L.append(f"")


def _emit_encoder_decoder_blocks(L, s, first_in, norm_type):
    """Emit encoder + decoder block loops."""
    # Encoder blocks
    L.append(f"  // Encoder blocks")
    L.append(f"  for (int i = 0; i < NUM_ENCODER_LAYERS; ++i) {{")
    L.append(f'    std::string enc_in = (i == 0) ? {first_in}')
    L.append(f'      : "enc_layer" + std::to_string(i - 1) '
             f'+ "_block_output";')
    L.append(f"    auto block = createEncoderBlock(i, enc_in);")
    L.append(f"    layers.insert(layers.end(), "
             f"block.begin(), block.end());")
    L.append(f"  }}")
    L.append(f"")

    # Encoder final norm
    L.append(f"  // Encoder final normalization")
    enc_norm_props = [
        'withKey("name", "encoder_output_norm")',
        'withKey("input_layers", "enc_layer" + '
        'std::to_string(NUM_ENCODER_LAYERS - 1) + "_block_output")',
        'withKey("epsilon", NORM_EPS)',
    ]
    if norm_type == "rms_norm":
        enc_norm_props.append('withKey("packed", "false")')
    elif norm_type == "layer_normalization":
        enc_norm_props.append('withKey("axis", 3)')
    L.extend(_cpp_layer(norm_type, enc_norm_props))
    L.append(f"")

    # Decoder blocks
    L.append(f"  // Decoder blocks")
    L.append(f"  for (int i = 0; i < NUM_DECODER_LAYERS; ++i) {{")
    L.append(f'    std::string dec_in = (i == 0) ? {first_in}')
    L.append(f'      : "dec_layer" + std::to_string(i - 1) '
             f'+ "_block_output";')
    L.append(f'    auto block = createDecoderBlock(i, dec_in, '
             f'"encoder_output_norm");')
    L.append(f"    layers.insert(layers.end(), "
             f"block.begin(), block.end());")
    L.append(f"  }}")
    L.append(f"")

    # Decoder final norm
    if s.final_norm:
        L.append(f"  // Decoder final normalization")
        dec_norm_props = [
            'withKey("name", "decoder_output_norm")',
            'withKey("input_layers", "dec_layer" + '
            'std::to_string(NUM_DECODER_LAYERS - 1) '
            '+ "_block_output")',
            'withKey("epsilon", NORM_EPS)',
        ]
        if norm_type == "rms_norm":
            dec_norm_props.append('withKey("packed", "false")')
        elif norm_type == "layer_normalization":
            dec_norm_props.append('withKey("axis", 3)')
        L.extend(_cpp_layer(norm_type, dec_norm_props))
        L.append(f"")


def _emit_hybrid_blocks(L, s, first_in, block_type, blocks_info):
    """Emit hybrid block loop (multiple operator types)."""
    op_type_list = blocks_info["op_type_list"]
    L.append(f"  // Layer types: {op_type_list}")
    L.append(f"  const std::vector<std::string> LAYER_TYPES = {{")
    for i, ot in enumerate(op_type_list):
        comma = "," if i < len(op_type_list) - 1 else ""
        L.append(f'    "{ot}"{comma}')
    L.append(f"  }};")
    L.append(f"")
    L.append(f"  // Hybrid blocks ({' + '.join(sorted(set(op_type_list)))})")
    L.append(f"  for (int i = 0; i < NUM_LAYERS; ++i) {{")
    L.append(f'    std::string input_name = (i == 0) ? {first_in}')
    L.append(f'      : "layer" + std::to_string(i - 1) '
             f'+ "_decoder_output";')
    L.append(f'    std::vector<LayerHandle> block;')

    for idx, op_type in enumerate(sorted(set(op_type_list))):
        op_label = op_type.capitalize() if op_type != "attention" \
            else "Transformer"
        method = (f"createTransformer{block_type}"
                  if op_type == "attention"
                  else f"create{op_label}{block_type}")
        keyword = "if" if idx == 0 else "} else if"
        L.append(f'    {keyword} (LAYER_TYPES[i] == "{op_type}") {{')
        L.append(f"      block = {method}(i, input_name);")
    L.append(f"    }}")

    L.append(f"    layers.insert(layers.end(), "
             f"block.begin(), block.end());")
    L.append(f"  }}")
    L.append(f"")


def _emit_standard_blocks(L, first_in, block_type):
    """Emit standard transformer block loop."""
    L.append(f"  // Transformer blocks")
    L.append(f"  for (int i = 0; i < NUM_LAYERS; ++i) {{")
    L.append(f'    std::string input_name = (i == 0) ? {first_in}')
    L.append(f'      : "layer" + std::to_string(i - 1) '
             f'+ "_decoder_output";')
    L.append(f"    auto block = createTransformer{block_type}"
             f"(i, input_name);")
    L.append(f"    layers.insert(layers.end(), "
             f"block.begin(), block.end());")
    L.append(f"  }}")
    L.append(f"")


def _emit_final_norm(L, norm_type):
    """Emit final normalization layer."""
    L.append(f"  // Final normalization")
    norm_props = [
        'withKey("name", "output_norm")',
        'withKey("input_layers", "layer" + '
        'std::to_string(NUM_LAYERS - 1)'
        ' + "_decoder_output")',
        'withKey("epsilon", NORM_EPS)',
    ]
    if norm_type == "rms_norm":
        norm_props.append('withKey("packed", "false")')
    elif norm_type == "layer_normalization":
        norm_props.append('withKey("axis", 3)')
    L.extend(_cpp_layer(norm_type, norm_props))
    L.append(f"")


def _emit_lm_head(L, s):
    """Emit LM head layer."""
    L.append(f"  // LM head")
    if s.tie_word_embeddings:
        L.append(f'  const std::string lmhead_type = '
                 f'TIE_WORD_EMBEDDINGS ? '
                 f'"tie_word_embeddings" : "fully_connected";')
    else:
        L.append(f'  const std::string lmhead_type = '
                 f'"fully_connected";')
    lm_input = ("decoder_output_norm" if s.arch_type == "encoder_decoder"
                else "output_norm")
    lm_props = [
        'withKey("name", "output_of_causallm")',
        'withKey("unit", NUM_VOCAB)',
        'withKey("disable_bias", "true")',
        f'withKey("input_layers", "{lm_input}")',
    ]
    if s.tie_word_embeddings:
        lm_props.append('withKey("shared_from", "embedding0")')
    L.extend(_cpp_layer("\" + lmhead_type + \"", lm_props))
    L.append(f"")
