"""C++ constructModel() method generation using symbolic Tensor API."""

from .helpers import (_cpp_layer, _cpp_tensor_layer, _class_name,
                      get_file_base, get_norm_type)


def emit_flat_source(layers, structure, model_name=None):
    """Generate source for non-transformer models (flat layer list)."""
    from .source_custom import emit_register_custom_layers
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    header_file = get_file_base(s, model_name) + ".h"

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type}")
    L.append(f"")
    L.append(f'#include "{header_file}"')
    L.append(f"#include <model.h>")
    L.append(f"#include <app_context.h>")
    L.append(f"#include <engine.h>")
    L.append(f"")
    L.append(f"using ml::train::createLayer;")
    L.append(f"")

    # withKey helpers (needed for initialize)
    L.append("template <typename T>")
    L.append("__attribute__((unused))")
    L.append('static std::string withKey(const std::string &key, T val) {')
    L.append('  return key + "=" + std::to_string(val);')
    L.append("}")
    L.append("")
    L.append("__attribute__((unused))")
    L.append("static std::string withKey(const std::string &key, "
             "const char *val) {")
    L.append('  return key + "=" + std::string(val);')
    L.append("}")
    L.append("")

    # Default constructor
    L.append(f"{cname}::{cname}() = default;")
    L.append(f"")

    L.append(f"void {cname}::constructModel() {{")
    L.append(f"")
    L.append(f"  // Create model")
    L.append(f"  model = ml::train::createModel("
             f"ml::train::ModelType::NEURAL_NET);")
    L.append(f"")

    # Build symbolic tensor graph from flat layer list
    L.append(f"  // Build symbolic tensor graph")
    # For flat models, we still use addLayer since layers have explicit
    # input_layers strings already set
    L.append(f"  std::vector<std::shared_ptr<ml::train::Layer>> layers;")
    L.append(f"")
    for layer in layers:
        L.append(f"  // {layer.layer_type}: {layer.name}")
        props = []
        for p in layer.to_properties_list():
            props.append(f'"{p}"')
        L.extend(_cpp_layer(layer.layer_type, props))
        L.append(f"")

    L.append(f"  // Add layers to model")
    L.append(f"  for (auto &layer : layers) {{")
    L.append(f"    model->addLayer(layer);")
    L.append(f"  }}")
    L.append(f"}}")
    L.append(f"")

    # registerCustomLayers (empty for flat models)
    L.append(emit_register_custom_layers(cname, []))

    # initialize (simplified for flat models - no INIT_SEQ_LEN)
    L.append(f"void {cname}::initialize() {{")
    L.append(f"  registerCustomLayers();")
    L.append(f"  constructModel();")
    L.append(f"")
    L.append(f"  model->setProperty({{")
    L.append(f'    withKey("batch_size", 1),')
    L.append(f'    withKey("epochs", "1"),')
    L.append(f'    withKey("model_tensor_type", "FP32-FP32")')
    L.append(f"  }});")
    L.append(f"")
    L.append(f"  if (model->compile(ml::train::ExecutionMode::INFERENCE)) {{")
    L.append(f'    throw std::invalid_argument("Model compilation failed.");')
    L.append(f"  }}")
    L.append(f"")
    L.append(f"  if (model->initialize(ml::train::ExecutionMode::INFERENCE)) {{")
    L.append(f'    throw std::invalid_argument("Model initialization failed.");')
    L.append(f"  }}")
    L.append(f"}}")
    L.append(f"")

    return "\n".join(L)


def emit_construct_model(structure, block_type, is_hybrid, blocks_info):
    """Generate constructModel() method body using symbolic Tensor API.

    Args:
        structure: ModelStructure
        block_type: "DecoderBlock", "Block", or None (encoder_decoder)
        is_hybrid: bool - whether model has multiple operator types
        blocks_info: dict with op_type_list, norm_type, etc.
    """
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    norm_type = get_norm_type(s.model_type)
    L = []

    L.append(f"void {cname}::constructModel() {{")
    L.append(f"")
    L.append(f"  // Create model")
    L.append(f"  model = ml::train::createModel("
             f"ml::train::ModelType::NEURAL_NET);")
    L.append(f"")

    # Symbolic input tensor
    L.append(f"  // Symbolic input tensor")
    L.append(f'  model_input_ = Tensor({{1, 1, 1, INIT_SEQ_LEN}}, "input0");')
    L.append(f"")

    # Embedding
    if s.embedding:
        _emit_embedding(L, s)

    first_var = "embedded" if s.embedding else "model_input_"

    # External KV cache input layers
    if s.external_kv_cache:
        _emit_external_kv_cache_inputs(L, s)

    if s.arch_type == "encoder_decoder":
        _emit_encoder_decoder_blocks(L, s, first_var, norm_type)
    elif is_hybrid:
        _emit_hybrid_blocks(L, s, first_var, block_type, blocks_info)
    else:
        _emit_standard_blocks(L, first_var, block_type)

    # Final norm (non-encoder-decoder)
    if s.arch_type != "encoder_decoder" and s.final_norm:
        _emit_final_norm(L, norm_type)

    # LM head
    if s.lm_head:
        _emit_lm_head(L, s)

    # Store model output (last computed tensor)
    # model_output_ is set by _emit_lm_head or _emit_final_norm
    L.append(f"}}")
    L.append(f"")
    return "\n".join(L)


def _emit_external_kv_cache_inputs(L, s):
    """Emit external KV cache allocation and input tensor creation."""
    L.append(f"  // External KV cache buffers")
    L.append(f"  size_t max_timestep = INIT_SEQ_LEN + NUM_TO_GENERATE;")
    L.append(f"  size_t kv_heads = NUM_KV_HEADS;")
    L.append(f"  size_t cache_size = 1 * kv_heads * max_timestep * HEAD_DIM;")
    L.append(f"  kv_cache_buffers.allocate(NUM_LAYERS, cache_size);")
    L.append(f"  key_cache_tensor_names.resize(NUM_LAYERS);")
    L.append(f"  val_cache_tensor_names.resize(NUM_LAYERS);")
    L.append(f"")
    L.append(f"  for (int i = 0; i < NUM_LAYERS; ++i) {{")
    L.append(f'    std::string k_name = "ext_cache_key_" + std::to_string(i);')
    L.append(f'    std::string v_name = "ext_cache_val_" + std::to_string(i);')
    L.append(f"    key_cache_tensor_names[i] = k_name;")
    L.append(f"    val_cache_tensor_names[i] = v_name;")
    L.append(f"  }}")
    L.append(f"")


def _emit_embedding(L, s):
    """Emit embedding layer section using symbolic tensor API."""
    L.append(f"  // Embedding layer")
    if s.tie_word_embeddings:
        L.append(f'  const std::string embedding_type = '
                 f'TIE_WORD_EMBEDDINGS ? '
                 f'"tie_word_embeddings" : "embedding_layer";')
        L.append(f"  LayerHandle embed_lh = createLayer(embedding_type, {{")
    else:
        L.append(f'  LayerHandle embed_lh = createLayer("embedding_layer", {{')
    L.append(f'    withKey("name", "embedding0"),')
    L.append(f'    withKey("in_dim", NUM_VOCAB),')
    L.append(f'    withKey("out_dim", DIM)')
    L.append(f"  }});")
    L.append(f"  auto embedded = embed_lh(model_input_);")
    L.append(f"")


def _emit_encoder_decoder_blocks(L, s, first_var, norm_type):
    """Emit encoder + decoder block loops using symbolic tensors."""
    # Encoder blocks
    L.append(f"  // Encoder blocks")
    L.append(f"  auto enc_x = {first_var};")
    L.append(f"  for (int i = 0; i < NUM_ENCODER_LAYERS; ++i) {{")
    L.append(f"    enc_x = createEncoderBlock(i, enc_x);")
    L.append(f"  }}")
    L.append(f"")

    # Encoder final norm
    L.append(f"  // Encoder final normalization")
    enc_norm_props = [
        'withKey("name", "encoder_output_norm")',
        'withKey("epsilon", NORM_EPS)',
    ]
    if norm_type == "rms_norm":
        enc_norm_props.append('withKey("packed", "false")')
    elif norm_type == "layer_normalization":
        enc_norm_props.append('withKey("axis", 3)')
    L.extend(_cpp_tensor_layer(norm_type, "encoder_normed",
                               enc_norm_props, "enc_x"))
    L.append(f"")

    # Decoder blocks
    L.append(f"  // Decoder blocks")
    L.append(f"  auto dec_x = {first_var};")
    L.append(f"  for (int i = 0; i < NUM_DECODER_LAYERS; ++i) {{")
    L.append(f"    dec_x = createDecoderBlock(i, dec_x, encoder_normed);")
    L.append(f"  }}")
    L.append(f"")

    # Decoder final norm
    if s.final_norm:
        L.append(f"  // Decoder final normalization")
        dec_norm_props = [
            'withKey("name", "decoder_output_norm")',
            'withKey("epsilon", NORM_EPS)',
        ]
        if norm_type == "rms_norm":
            dec_norm_props.append('withKey("packed", "false")')
        elif norm_type == "layer_normalization":
            dec_norm_props.append('withKey("axis", 3)')
        L.extend(_cpp_tensor_layer(norm_type, "x", dec_norm_props, "dec_x"))
        L.append(f"")


def _emit_hybrid_blocks(L, s, first_var, block_type, blocks_info):
    """Emit hybrid block loop (multiple operator types) using symbolic tensors."""
    op_type_list = blocks_info["op_type_list"]
    L.append(f"  // Layer types: {op_type_list}")
    L.append(f"  const std::vector<std::string> LAYER_TYPES = {{")
    for i, ot in enumerate(op_type_list):
        comma = "," if i < len(op_type_list) - 1 else ""
        L.append(f'    "{ot}"{comma}')
    L.append(f"  }};")
    L.append(f"")
    L.append(f"  // Hybrid blocks ({' + '.join(sorted(set(op_type_list)))})")
    L.append(f"  auto x = {first_var};")
    L.append(f"  for (int i = 0; i < NUM_LAYERS; ++i) {{")

    for idx, op_type in enumerate(sorted(set(op_type_list))):
        op_label = op_type.capitalize() if op_type != "attention" \
            else "Transformer"
        method = (f"createTransformer{block_type}"
                  if op_type == "attention"
                  else f"create{op_label}{block_type}")
        keyword = "if" if idx == 0 else "} else if"
        L.append(f'    {keyword} (LAYER_TYPES[i] == "{op_type}") {{')
        L.append(f"      x = {method}(i, x);")
    L.append(f"    }}")

    L.append(f"  }}")
    L.append(f"")


def _emit_standard_blocks(L, first_var, block_type):
    """Emit standard transformer block loop using symbolic tensors."""
    L.append(f"  // Transformer blocks")
    L.append(f"  auto x = {first_var};")
    L.append(f"  for (int i = 0; i < NUM_LAYERS; ++i) {{")
    L.append(f"    x = createTransformer{block_type}(i, x);")
    L.append(f"  }}")
    L.append(f"")


def _emit_final_norm(L, norm_type):
    """Emit final normalization layer using symbolic tensor API."""
    L.append(f"  // Final normalization")
    norm_props = [
        'withKey("name", "output_norm")',
        'withKey("epsilon", NORM_EPS)',
    ]
    if norm_type == "rms_norm":
        norm_props.append('withKey("packed", "false")')
    elif norm_type == "layer_normalization":
        norm_props.append('withKey("axis", 3)')
    L.extend(_cpp_tensor_layer(norm_type, "x", norm_props, "x"))
    L.append(f"")


def _emit_lm_head(L, s):
    """Emit LM head layer using symbolic tensor API."""
    L.append(f"  // LM head")
    if s.tie_word_embeddings:
        L.append(f'  const std::string lmhead_type = '
                 f'TIE_WORD_EMBEDDINGS ? '
                 f'"tie_word_embeddings" : "fully_connected";')
    else:
        L.append(f'  const std::string lmhead_type = '
                 f'"fully_connected";')
    lm_props = [
        'withKey("name", "output_of_causallm")',
        'withKey("unit", NUM_VOCAB)',
        'withKey("disable_bias", "true")',
    ]
    if s.tie_word_embeddings:
        lm_props.append('withKey("shared_from", "embedding0")')
    if s.tie_word_embeddings:
        L.append(f"  LayerHandle lm_head_lh = createLayer(lmhead_type, {{")
    else:
        L.append(f'  LayerHandle lm_head_lh = createLayer(lmhead_type, {{')
    for i, p in enumerate(lm_props):
        comma = "," if i < len(lm_props) - 1 else ""
        L.append(f"    {p}{comma}")
    L.append(f"  }});")
    L.append(f"  model_output_ = lm_head_lh(x);")
    L.append(f"")
