"""C++ source generation for Transformer-inheriting models.

Generates only the overridden methods (createAttention, registerCustomLayers)
and a test factory method. The base class (CausalLM/Transformer) provides
constructModel(), createTransformerDecoderBlock(), createMlp(), initialize(),
load_weight(), run(), etc.
"""

from .helpers import _class_name, _cpp_tensor_layer, get_file_base, get_norm_type
from .source_attention import emit_attention_method
from .source_ffn import emit_ffn_method
from .source_custom import (
    collect_custom_layer_classes, emit_custom_layer_includes,
    CUSTOM_LAYER_CLASS,
)


def emit_inherit_source(structure, attn_block, custom_classes, model_name):
    """Generate source file for Transformer-inheriting model.

    Only emits methods that differ from the base Transformer class:
    - createAttention() if model has QK norms or other attention differences
    - createMlp() if model has non-standard FFN (e.g., GELU instead of SwiGLU)
    - registerCustomLayers() to register model-specific custom layers
    - createTestModel() static factory for standalone testing
    """
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    header_file = get_file_base(s, model_name) + ".h"
    norm_type = get_norm_type(s.model_type)

    has_lm_head = bool(s.lm_head)
    has_qk_norm = attn_block and attn_block.attention.has_qk_norm
    need_variant = has_qk_norm

    if has_lm_head and s.arch_type == "decoder_only":
        base_class = "CausalLM"
    else:
        base_class = "Transformer"

    variant_name = cname.replace("CausalLM", "Transformer").replace(
        "Model", "Transformer") if need_variant else None

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type} ({s.arch_type})")
    L.append(f"// Inherits from causallm::{base_class}")
    L.append(f"")
    L.append(f'#include "{header_file}"')
    L.append(f"#include <model.h>")
    L.append(f"#include <tensor_api.h>")
    L.append(f"#include <app_context.h>")
    L.append(f"#include <engine.h>")
    L.append(f"")

    includes = emit_custom_layer_includes(custom_classes)
    if includes:
        L.append(includes)
        L.append(f"")

    L.append(f"using ml::train::createLayer;")
    L.append(f"using ml::train::Tensor;")
    L.append(f"using LayerHandle = ml::train::LayerHandle;")
    L.append(f"")

    # withKey helper templates
    L.append("template <typename T>")
    L.append('static std::string withKey(const std::string &key, T val) {')
    L.append('  return key + "=" + std::to_string(val);')
    L.append("}")
    L.append("")
    L.append("template <>")
    L.append('std::string withKey(const std::string &key, '
             'std::string val) {')
    L.append('  return key + "=" + val;')
    L.append("}")
    L.append("")
    L.append("template <>")
    L.append('std::string withKey(const std::string &key, '
             'const char *val) {')
    L.append('  return key + "=" + std::string(val);')
    L.append("}")
    L.append("")

    L.append(f"namespace causallm {{")
    L.append(f"")

    # --- Variant class methods (e.g., Qwen3Transformer::createAttention) ---
    if need_variant:
        # createAttention override on variant class
        if attn_block:
            attn_code = emit_attention_method(
                variant_name, attn_block,
                arch_type=s.arch_type,
                external_kv_cache=s.external_kv_cache)
            L.append(attn_code)

        # registerCustomLayers for variant
        L.append(f"void {variant_name}::registerCustomLayers() {{")
        # Register only variant-specific layers (e.g., ReshapedRMSNorm)
        variant_classes = set()
        if has_qk_norm:
            variant_classes.add("ReshapedRMSNormLayer")
        _emit_layer_registration(L, sorted(variant_classes))
        L.append(f"}}")
        L.append(f"")

    # --- Main class methods ---

    # registerCustomLayers: combines base + variant registrations
    L.append(f"void {cname}::registerCustomLayers() {{")
    if need_variant:
        L.append(f"  {base_class}::registerCustomLayers();")
        L.append(f"  {variant_name}::registerCustomLayers();")
    else:
        L.append(f"  {base_class}::registerCustomLayers();")
        # Register any extra custom layers not in base
        extra = _get_extra_custom_classes(custom_classes, base_class)
        if extra:
            _emit_layer_registration(L, extra)
    L.append(f"}}")
    L.append(f"")

    # If model has non-standard FFN and no variant handles it, emit createMlp
    ffn_block = next((b for b in s.blocks if b.ffn), None)
    if ffn_block and ffn_block.ffn.ffn_type not in ("swiglu",):
        L.append(emit_ffn_method(cname, ffn_block))

    # createTestModel: factory method for standalone testing
    _emit_test_factory(L, cname, s, need_variant, base_class, variant_name)

    L.append(f"}} // namespace causallm")
    L.append(f"")
    return "\n".join(L)


def _emit_layer_registration(L, classes):
    """Emit registerFactory calls for a set of custom layer classes."""
    L.append(f"  auto &ct_engine = nntrainer::Engine::Global();")
    L.append(f'  auto app_context =')
    L.append(f'    static_cast<nntrainer::AppContext *>('
             f'ct_engine.getRegisteredContext("cpu"));')
    L.append(f"  try {{")
    for cls in classes:
        L.append(f"    app_context->registerFactory("
                 f"nntrainer::createLayer<causallm::{cls}>);")
    L.append(f"  }} catch (std::invalid_argument &e) {{")
    L.append(f'    std::cerr << "failed to register factory, reason: " '
             f'<< e.what() << std::endl;')
    L.append(f"  }}")


def _get_extra_custom_classes(all_classes, base_class):
    """Return custom classes that aren't already registered by the base."""
    # Base Transformer registers: SwiGLU, RMSNorm, MHACore,
    # TieWordEmbedding, Embedding
    # CausalLM also registers: LmHead
    base_registered = {
        "SwiGLULayer", "RMSNormLayer", "MHACoreLayer",
        "TieWordEmbedding", "EmbeddingLayer",
    }
    if base_class == "CausalLM":
        base_registered.add("LmHeadLayer")
    return sorted(set(all_classes) - base_registered)


def _emit_test_factory(L, cname, s, need_variant, base_class, variant_name):
    """Emit createTestModel() static factory for standalone testing."""
    L.append(f"{cname} {cname}::createTestModel() {{")
    L.append(f"  // Minimal JSON config for testing")
    L.append(f"  json cfg;")
    L.append(f'  cfg["vocab_size"] = {s.vocab_size};')
    L.append(f'  cfg["hidden_size"] = {s.hidden_size};')
    L.append(f'  cfg["num_hidden_layers"] = {min(s.num_layers, 2)};')
    L.append(f'  cfg["num_attention_heads"] = {s.num_heads};')
    L.append(f'  cfg["num_key_value_heads"] = {s.num_kv_heads};')
    L.append(f'  cfg["head_dim"] = {s.head_dim};')
    L.append(f'  cfg["intermediate_size"] = {s.intermediate_size};')
    if s.rope_theta:
        L.append(f'  cfg["rope_theta"] = {int(s.rope_theta)};')
    L.append(f'  cfg["rms_norm_eps"] = {s.norm_eps or 1e-6};')
    L.append(f'  cfg["tie_word_embeddings"] = '
             f'{"true" if s.tie_word_embeddings else "false"};')
    if s.max_position_embeddings:
        L.append(f'  cfg["max_position_embeddings"] = '
                 f'{s.max_position_embeddings};')
    L.append(f"")
    L.append(f"  json gen_cfg;")
    L.append(f'  gen_cfg["max_new_tokens"] = 1;')
    L.append(f"")
    L.append(f"  json nntr_cfg;")
    L.append(f'  nntr_cfg["init_seq_len"] = 8;')
    L.append(f'  nntr_cfg["batch_size"] = 1;')
    L.append(f'  nntr_cfg["model_tensor_type"] = "FP32-FP32";')
    L.append(f'  nntr_cfg["memory_swap"] = false;')
    L.append(f'  nntr_cfg["tokenizer_file"] = "";')
    L.append(f"")
    L.append(f"  return {cname}(cfg, gen_cfg, nntr_cfg);")
    L.append(f"}}")
    L.append(f"")
