// Auto-generated by TorchFX-to-NNTrainer converter
// Model: granitemoehybrid (decoder_only)

#ifndef __GRANITE_40_VERIFY_H__
#define __GRANITE_40_VERIFY_H__

#include <climits>
#include <layer.h>
#include <model.h>
#include <tensor_api.h>

using LayerHandle = ml::train::LayerHandle;
using Tensor = ml::train::Tensor;
using ModelHandle = std::unique_ptr<ml::train::Model>;

/**
 * @brief GraniteCausalLM Class
 * @note Auto-generated from HuggingFace granitemoehybrid model
 */
class GraniteCausalLM {

public:
  GraniteCausalLM();
  virtual ~GraniteCausalLM() = default;

  /**
   * @brief Construct the model graph
   */
  virtual void constructModel();

  /**
   * @brief Initialize the model (register layers, construct, compile)
   */
  virtual void initialize();

  /**
   * @brief Get the underlying model handle
   */
  ModelHandle &getModel() { return model; }

protected:
  /**
   * @brief Create a Transformer DecoderBlock
   */
  virtual Tensor
  createTransformerDecoderBlock(const int layer_id, Tensor input);

  /**
   * @brief Create Attention layers
   */
  virtual Tensor
  createAttention(const int layer_id, int seq_len, int n_heads, int head_dim,
                  Tensor query, Tensor key, Tensor value);

  /**
   * @brief Create Feed Forward layers
   */
  virtual Tensor
  createMlp(const int layer_id, int dim, int hidden_dim,
            Tensor input);

  /**
   * @brief Register custom layers
   */
  virtual void registerCustomLayers();

  ModelHandle model;

  // Model constants
  unsigned int NUM_VOCAB = 1000;
  int DIM = 64;
  int NUM_LAYERS = 2;
  int NUM_HEADS = 4;
  int NUM_KV_HEADS = 2;
  int HEAD_DIM = 16;
  int INTERMEDIATE_SIZE = 1024;
  std::string NORM_EPS = "1e-05";
  unsigned int ROPE_THETA = 10000;
  bool TIE_WORD_EMBEDDINGS = true;
  int GQA_SIZE = 2;
  unsigned int SLIDING_WINDOW = UINT_MAX;
  unsigned int INIT_SEQ_LEN = 0;
  unsigned int NUM_TO_GENERATE = 1;
  unsigned int MAX_POSITION_EMBEDDINGS = 128;
};

#endif // __GRANITE_40_VERIFY_H__
